version: "3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ### COMPOSER ##############################################
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer-dev-candy
    command: >
      sh -c "
      ssh-keyscan -t rsa gitlab.lynxsolutions.eu | tee /root/.ssh/known_hosts &&
      composer install --ignore-platform-reqs --no-scripts --no-suggest &&
      composer dump-auto &&
      sleep 1000d"
    working_dir: /app
    volumes:
      - ./.ssh:/root/.ssh
      - ./src:/app

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
        - INSTALL_XDEBUG=false
    user: ${UID}
    ports:
        - "5173:5173"
    volumes:
      - ./src:/app
    environment:
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - backend

  ### NGINX Server #########################################
  passkey-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf:ro
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_EXPOSE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
